[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version ="0.12.8", features = ["json"] }
rocket = "0.5.1"
tokio = { version = "1", features = ["full"] }
warp = "0.3"